name: ic_tools
# description: 
version: 0.9.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  http: ^0.13.3
  cbor: 4.0.2
  leb128: ^1.0.1
  crypto: ^3.0.1 #maybe only 1 crypto lib
  typed_data: ^1.3.0 #check if use
  archive: ^3.1.2 # check if use 
  base32: ^1.1.0
  cryptography: 2.0.1 
  ffi: ^1.0.0
  js: ^0.6.3
